image: golang:1.21

stages:
  - test
  - build
  - deploy

run-test:
  stage: test
  script: go test -v  ./...

build-app:
  stage: build
  script: go build -o tmanager .

deploy-to-server:
  stage: deploy
  only: [main]
  when: manual
  script: echo "hello from deploy"




















