version: '3.9'
services:
  db:
    image: postgres:15.6
    container_name: tmanager-db
    ports:
      - '8014:5432'
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: dev
    restart: always
    volumes:
      - tmdb:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.7
    container_name: tmanager-kafka
    hostname: localhost
    ports:
      - '9092:9092'
    networks:
      - app
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    restart:  always

  redis:
    image: redis:7.2.4
    container_name: tmanager-redis
    ports:
      - '6379:6379'
    networks:
      - app
    restart: always
networks:
  app:
volumes:
  tmdb:
