openapi: "3.0.2"

info:
  title: Task manager API
  version: 1.0.0
  description: Task manager can work with tasks

servers:
  - url: http://localhost:8021

paths:
  /tasks:
    get:
      summary: "get all tasks"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 12
                    name:
                      type: string
                      example: buy milk
                    status:
                      type: string
                      enum:
                        - not_done
                        - done
                    created_at:
                      type: string
                      format: date-time
                    user_id:
                      type: integer
                      format: int64
                      example: 105
